# Сбалансированная конфигурация SAC для честного сравнения

algorithm:
  name: "SAC"
  
  # Архитектура - одинаковая для всех
  hidden_dim: 128                   # Единый размер
  
  # Гиперпараметры обучения
  learning_rate: 0.0003
  gamma: 0.99
  tau: 0.005
  alpha: 0.2
  automatic_entropy_tuning: true
  
  # Replay buffer
  buffer_size: 100000               # Оптимизировано
  batch_size: 128                   # Увеличен для стабильности
  
  # Параметры обучения
  total_timesteps: 200000           # Одинаково для всех
  learning_starts: 5000             # Меньше, чтобы начать раньше
  train_frequency: 1
  gradient_steps: 1
  
  device: "cpu"

