# Сбалансированная конфигурация A2C для честного сравнения

algorithm:
  name: "A2C"
  
  # Архитектура - одинаковая для всех
  hidden_dim: 128                   # Единый размер для всех алгоритмов
  
  # Гиперпараметры обучения
  learning_rate: 0.0003
  gamma: 0.99
  
  # A2C специфичные
  vf_coef: 0.5
  ent_coef: 0.01
  max_grad_norm: 0.5
  
  # Параметры обучения - настроены для ~200K timesteps
  total_timesteps: 200000           # Одинаково для всех
  num_steps: 5                      # Rollout size (короче чем у PPO)
  
  device: "cpu"

