# Сбалансированная конфигурация DDPG для честного сравнения

algorithm:
  name: "DDPG"
  
  # Архитектура - одинаковая для всех
  hidden_dim: 128                   # Единый размер для всех алгоритмов
  
  # Гиперпараметры обучения
  actor_learning_rate: 0.0003
  critic_learning_rate: 0.0003
  gamma: 0.99
  tau: 0.005                        # Soft update coefficient
  
  # Buffer
  buffer_size: 1000000              # Как у SAC/TD3
  batch_size: 128                   # Балансируем с другими
  
  # Training
  total_timesteps: 200000           # Одинаково для всех
  learning_starts: 1000             # Warm-up
  train_freq: 1                     # Update each step
  
  # Exploration
  exploration_noise: 0.1            # Gaussian noise std
  
  device: "cpu"

