# Полная конфигурация эксперимента (среда + алгоритм)

environment:
  area_size: 1.0
  n_obstacles: 5
  obstacle_radius_range: [0.05, 0.15]
  max_episode_steps: 500
  agent_max_speed: 0.02
  agent_max_accel: 0.002
  agent_radius: 0.01
  target_speed: 0.01
  interception_radius: 0.03
  collision_penalty: -10.0
  time_penalty: -0.01
  success_reward: 100.0
  seed: 42

algorithm:
  name: "PPO"
  hidden_dim: 64
  learning_rate: 0.0003
  gamma: 0.99
  gae_lambda: 0.95
  clip_coef: 0.2
  vf_coef: 0.5
  ent_coef: 0.01
  max_grad_norm: 0.5
  total_timesteps: 100000
  num_steps: 2048
  batch_size: 64
  num_epochs: 10
  device: "cpu"

