# Длительное обучение SAC - 1M timesteps

algorithm:
  name: "SAC"
  
  # Увеличенная архитектура для лучшего обучения
  hidden_dim: 256                   # Увеличено с 128
  
  # Гиперпараметры обучения
  learning_rate: 0.0003
  gamma: 0.99
  tau: 0.005
  alpha: 0.2
  automatic_entropy_tuning: true
  
  # Replay buffer - увеличен для 1M timesteps
  buffer_size: 500000               # Увеличено для длительного обучения
  batch_size: 256                   # Увеличен для стабильности
  
  # Параметры обучения
  total_timesteps: 1000000          # Увеличено с 200K
  learning_starts: 10000            # Больше прогрева
  train_frequency: 1
  gradient_steps: 1
  
  device: "cpu"


