# Конфигурация SAC алгоритма

algorithm:
  name: "SAC"
  
  # Архитектура нейронной сети
  hidden_dim: 256                   # Размер скрытого слоя
  
  # Гиперпараметры обучения
  learning_rate: 0.0003             # Learning rate
  gamma: 0.99                       # Discount factor
  tau: 0.005                        # Soft update coefficient
  alpha: 0.2                        # Entropy temperature
  automatic_entropy_tuning: true    # Автоматическая настройка температуры
  
  # Replay buffer
  buffer_size: 1000000              # Размер replay buffer
  batch_size: 256                   # Размер батча для обучения
  
  # Параметры обучения
  total_timesteps: 100000           # Общее количество шагов обучения
  learning_starts: 1000             # Шагов до начала обучения
  train_frequency: 1                # Частота обновления (каждый N шагов)
  gradient_steps: 1                 # Градиентных шагов на каждое обновление
  
  # Device
  device: "cpu"                     # "cpu" или "cuda"

