# Extreme scenario - очень сложная среда

environment:
  area_size: 1.0
  n_obstacles: 15                      # Очень много препятствий
  obstacle_radius_range: [0.06, 0.18]  # Крупные препятствия
  max_episode_steps: 600               # Больше времени
  agent_max_speed: 0.018               # Медленнее агент
  agent_max_accel: 0.0018
  agent_radius: 0.012                  # Больший радиус агента
  target_speed: 0.015                  # Быстрая цель
  interception_radius: 0.025           # Меньший радиус перехвата
  collision_penalty: -20.0             # Очень большой штраф
  time_penalty: -0.015                 # Больший штраф за время
  success_reward: 200.0                # Максимальная награда
  seed: 42

